### ISSUE TITLE
Execute `select` query can not autocommit.

### ISSUE THREAD

**Issue by uimeet** [webpy/webpy#585] opened 2019-11-29 06:14 UTC
The code position at **lines 848** in `db.py`.

`return self.create_result_set(db_cursor)`
to
`out = self.create_result_set(db_cursor)`

**Comment by iredmail** [comment] 2019-11-29 06:31
Duplicate of https://github.com/webpy/webpy/pull/584

**Closed by iredmail** 2019-11-29 06:31 UTC
