### ISSUE TITLE
Automatic Database Closing

### ISSUE THREAD

**Issue by micahschaefer** [webpy/webpy#251] opened 2013-10-08 12:25 UTC
I could not find in the source code anywhere that the database connection is actually closed. At least when using a mysql database, this results in aborted clients. 

In the DB class, if you attempt to call ctx.db.close() if close is an available function, it cleanly closes the db connection and releases those resources. 

Please think about adding code similar to :

<code>
class DB:
 def **del**(self):
  ctx.close()
</code>

**Comment by zhanghuangbin** [comment] 2015-03-07 06:04
Dear Anand,

I had this issue too, and it's some kind of critical.

I have a small socket daemon, it starts a new SQL connection for a new request, but after request, webpy doesn't close the sql connection.

We cannot wait until when ctx is garbage collected, it will cause too many sql connection to SQL server (e.g. MySQL). If SQL server has connection limit, my program will soon stop working with error message like `too many connection to sql server`, and new request cannot be processed.

Please, add a method to allow user to close db connection manually and immediately.

**Comment by anandology** [comment] 2015-03-07 06:09
I think you can do `db.ctx.db.close()` to explicitly close the connection.

I'll look into this issue in more detail shortly. Do you have some code to
reproduce this?


On Sat, Mar 7, 2015 at 11:34 AM, Zhang Huangbin <notifications@github.com>
wrote:

> Dear Anand,
>
> I had this issue too, and it's some kind of critical.
>
> I have a small socket daemon, it starts a new SQL connection for a new
> request, but after request, webpy doesn't close the sql connection.
>
> We cannot wait until when ctx is garbage collected, it will cause too many
> sql connection to SQL server (e.g. MySQL). If SQL server has connection
> limit, my program will soon stop working with error message like too many
> connection to sql server, and new request cannot be processed.
>
> Please, add a method to allow user to close db connection manually and
> immediately.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/webpy/webpy/issues/251#issuecomment-77675584>.
>



-- 
Anand
http://anandology.com/

**Comment by zhanghuangbin** [comment] 2015-03-07 06:15
Unfortunately, I don't have the code to reproduce this issue right now, because i rewrote the code to use MySQLdb module directly (so that i can close the sql connection manually/immediately). But i really want to use webpy in my code, because it's much simpler.

Maybe @kulous has some code to reproduce this issue?

**Comment by zhanghuangbin** [comment] 2015-03-07 06:26
OK, i wrote some code to reproduce this issue:

* webpy code:

```python
import web
web.config.debug = False

class SQLWrap(object):
    def __init__(self):
        self.conn = web.database(
            dbn='mysql',
            host='127.0.0.1',
            port=3306,
            db='vmail',
            user='root',
            pw='password',
        )

for i in range(1000):
	sql = SQLWrap()
	qr = sql.conn.select('mailbox', what='username', limit=1)
```

* MySQL connection is limit to 100 in `my.cnf`:

```
[mysqld]
max_connections        = 100
...
```

* Run above webpy code, you will get error like this when sql connection reaches 100: `_mysql_exceptions.OperationalError: (1040, 'Too many connections')`

**Comment by zhanghuangbin** [comment] 2015-03-07 06:34
Oh, looks like we can close it with below code:

```python
class SQLWrap(object):
    def __del__(self):
        self.conn.ctx.db.close()
```

**Comment by zhanghuangbin** [comment] 2015-03-07 07:09
I created two pull requests for documents you can merge directly:

1) webpy:
https://github.com/webpy/webpy/pull/322

2) webpy.github.com:
https://github.com/webpy/webpy.github.com/pull/102

And we can close this issue now.

**Comment by anandology** [comment] 2015-03-16 17:31
There seems to be a leak and that should be fixed, but why are you creating so many database objects? Isn't it better to create one database object and work with it?

**Comment by kulous** [comment] 2015-03-29 03:28
Disclaimer: I haven't used this library in over 6 months

I issued a pull request for my patch. Let me know your thoughts. As the PR states, I was multi-threading which would rapidly create database connections, destroy them, create new ones, and so forth. MySQL would crash pretty quickly

**Closed** 2019-06-04 03:08 UTC
