### ISSUE TITLE
Session Cookie should optionally have longer expiration date

### ISSUE THREAD

**Issue by despens** [webpy/webpy#99] opened 2011-09-21 08:40 UTC
To have session cookies last longer than until the browser is closed is useful in many cases. For example that uses do not have to log on every time they come to a site that is some kind of web service.

The cookie set by session should respect what is contained in the session "timeout" parameter, so for example

```
 web.config.session_parameters['timeout'] = (60 * 60 * 24 * 365 * 5)
```

should make cookies lasting for 5 years.

Otherwise, one would have to manually replicate the complete session system.

Google Groups thread about it here: http://groups.google.com/group/webpy/browse_thread/thread/cd88e2f13947223b

**Comment by danagilliann** [comment] 2018-03-02 22:09
Hello! Just adding that this is a duplicate of #61 so people don't get confused :)

**Closed** 2019-09-16 04:47 UTC
Labels: Session / Cookie
