### ISSUE TITLE
len(<web.db.ResultSet>) doesn't work before first access

### ISSUE THREAD

**Issue by berkakinci** [webpy/webpy#587] opened 2020-01-03 15:25 UTC
It appears there is a hook in ResultSet to get number of rows using len() function.  It was recently touched in response to issue #547 .
However, len()  only works after an access to an item in the result set.  It seems less useful that way, and also probably not what was intended.

Here's an example reproduction:
```
Python 3.5.3 (default, Sep 27 2018, 17:25:39)
…
>>> import web
>>> web.__version__
'0.40'
>>> db=web.database(dbn='mysql',
...
...                 port=3306)
>>> rs=db.select('Users', what='*', where='User_Name="root"')
0.0 (1): SELECT * FROM Users WHERE User_Name="root"
>>> len(rs)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: __len__() should return >= 0
>>> print(rs.names)
['user_id', …]
>>> len(rs)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: __len__() should return >= 0
>>> print(rs.list())
[<Storage {…, 'user_id': 0}>]
>>> len(rs)
1
```
My expectation: len() works even before I've already accessed the results.  (I.e. no exception)

**Comment by berkakinci** [comment] 2020-01-03 18:40
This also breaks sessions when using DBStore.  Same exception is thrown at DBStore.__contains__() when executing "return(bool(list(data)))"

**Comment by berkakinci** [comment] 2020-01-03 19:22
I dug into this some more.  Here is another bit of relevant information:
```
>>> print(db.db_module)
<module 'mysql.connector' from '/usr/lib/python3/dist-packages/mysql/connector/__init__.py'>
 ```
The cursor.rowcount property from this connector is "-1" when not in buffered mode.  See:
[https://dev.mysql.com/doc/connector-python/en/connector-python-api-mysqlcursor-rowcount.html](url)

For now, I'm working around this issue by enabling buffered cursors (`buffered=True`) such as:
```
Python 3.5.3 (default, Sep 27 2018, 17:25:39)
>>> import web
>>> db=web.database(dbn='mysql',
…
...                 port=3306,
...                 buffered=True)
>>> rs=db.select('Users')
0.0 (1): SELECT * FROM Users
>>> len(rs)
1
```
I would like to see a more transparent fix, but this should be OK for me for now.

**Comment by berkakinci** [comment] 2020-01-04 20:07
Please revert the checkin [https://github.com/webpy/webpy/commit/b72ced8df96466a7e4a31630f606a81567524391](url)
It will eliminate the exception, but it does not fix the bug.  It'll be a lot harder to debug this in the future.
For example, with this checkin, mysql.connector and un-buffered cursors: DBStore.__contains__() will always return "False" and cause session_id to never be found.  Silently!
In the context of "mysql.connector" using non-buffered cursors, __contains__() could use property cursor.with_rows to get a valid result.
However, I haven't seen anything that can "look ahead" and fix the cursor.rowcount property.  I would rather see a more meaningful exception message than propagating an incorrect __len__() result.

**Comment by iredmail** [comment] 2020-01-11 08:45
Cc @anandology

**Comment by wangjing1215** [comment] 2020-02-24 14:49
File "/usr/lib/python2.7/site-packages/web/utils.py", line 709, in __nonzero__
    return len(self) != 0
TypeError: __len__() should return an int
when I use like this:
re = db.query("select 1 from user")
if re:

sometime will get  error.how to fix it?

**Comment by anandology** [comment] 2020-03-05 05:29
Seems to be working file with postgres:

```
>>> import web
>>> db=web.database(dbn='postgres', db='test')
>>> result = db.query("select 1 as x")
0.05 (1): select 1 as x
>>> len(result)
1
```

The issue seems to be with the `mysql.connector`  library.

```
>>> db = web.database(dbn="mysql", host="127.0.0.1", user="root", pw="")
>>> rs = db.query("select 1 as x")
0.0 (1): select 1 as x
>>> rs.cursor.rowcount
-1
```

The cursor is returning rowcount as -1 until the data is read. 

```
>>> rs.cursor.fetchone()
(1,)
>>> rs.cursor.rowcount
1
```

As @berkakinci  pointed out, the issue is we are using mysql.connector with unbuffered cursor.

The following StackOverflow thread explains it clearly.
https://stackoverflow.com/questions/46682012/what-is-a-mysql-buffered-cursor-w-r-t-python-mysql-connector

To fix this, we need to create buffered cursor using `conn.cursor(buffered=True)`, which doesn't seem to the standard Python DB API.  I'll explore further to see if there is a more elegant way to address this.

**Comment by anandology** [comment] 2020-03-05 05:32
Found it. Passing `buffered=True` when creating the database does the trick.

```
>>> db = web.database(dbn="mysql", host="127.0.0.1", user="root", pw="", buffered=True)
>>>
>>> rs = db.query("select 1 as x")
0.0 (1): select 1 as x
>>> len(rs)
1
```

**Comment by iredmail** [comment] 2020-03-05 05:59
Great, maybe tag a new release after this fix?
@cclauss @anandology

**Comment by anandology** [comment] 2020-03-05 06:20
I've pushed a fix. Can someone else test and confirm?

**Comment by anandology** [comment] 2020-03-05 06:21
> Great, maybe tag a new release after this fix?
> @cclauss @anandology

The tests are broken. It would be a good idea to convert the tests to py.test and setup github actions for CI.

**Closed** 2020-03-19 15:55 UTC
